package ag.act.facade.batch;

public interface IBatchGroupName {

    String DIGITAL_DOCUMENT_USERS = "DIGITAL_DOCUMENT_USERS";
    String UPDATE_TEST_STOCKS = "UPDATE_TEST_STOCKS";
    String USER_HOLDING_STOCK_HISTORIES = "USER_HOLDING_STOCK_HISTORIES";
    String STOCK_RANKINGS = "STOCK_RANKINGS";
    String SEND_PUSHES = "SEND_PUSHES";
    String UPDATE_WITHDRAWAL_REQUEST_USERS = "UPDATE_WITHDRAWAL_REQUEST_USERS";
    String SOLIDARITY_DAILY_SUMMARIES = "SOLIDARITY_DAILY_SUMMARIES";
    String SOLIDARITY_DAILY_STATISTICS = "SOLIDARITY_DAILY_STATISTICS";
    String UPDATE_STOCKS = "UPDATE_STOCKS";
    String DELETE_OLD_DIGITAL_DOCUMENT = "DELETE_OLD_DIGITAL_DOCUMENT";
    String DIGITAL_DOCUMENT_ZIP_FILE = "DIGITAL_DOCUMENT_ZIP_FILE";
    String DASHBOARD_STATISTICS = "DASHBOARD_STATISTICS";
    String UPDATE_DART = "UPDATE_DART";
    String SOLIDARITY_LEADER_ELECTIONS = "SOLIDARITY_LEADER_ELECTIONS";
}
