package ag.act.facade.batch;

public interface IBatchName {

    String UPDATE_STOCKS = "UPDATE_STOCKS";
    String DELETE_OLD_DIGITAL_DOCUMENT = "DELETE_OLD_DIGITAL_DOCUMENT";
    String CREATE_SOLIDARITY_DAILY_STATISTICS = "CREATE_SOLIDARITY_DAILY_STATISTICS";
    String CREATE_SOLIDARITY_DAILY_SUMMARIES = "CREATE_SOLIDARITY_DAILY_SUMMARIES";
    String UPDATE_SOLIDARITY_DAILY_SUMMARIES = "UPDATE_SOLIDARITY_DAILY_SUMMARIES";
    String UPDATE_WITHDRAWAL_REQUEST_USERS = "UPDATE_WITHDRAWAL_REQUEST_USERS";
    String SEND_PUSHES = "SEND_PUSHES";
    String STOCK_RANKINGS = "STOCK_RANKINGS";
    String USER_HOLDING_STOCK_HISTORIES = "USER_HOLDING_STOCK_HISTORIES";
    String CLEANUP_UNFINISHED_DIGITAL_DOCUMENT_USERS = "CLEANUP_UNFINISHED_DIGITAL_DOCUMENT_USERS";
    String UPDATE_TEST_STOCKS = "UPDATE_TEST_STOCKS";
    String CLEANUP_UNFINISHED_BATCHES = "CLEANUP_UNFINISHED_BATCHES";
    String UPDATE_DART_CORP_CODE = "UPDATE_DART_CORP_CODE";
    String UPDATE_DART_CORPORATIONS = "UPDATE_DART_CORPORATIONS";
    String UPDATE_STOCKS_FROM_DART_CORPORATIONS = "UPDATE_STOCKS_FROM_DART_CORPORATIONS";
    String DIGITAL_DOCUMENT_ZIP_FILE = "DIGITAL_DOCUMENT_ZIP_FILE";
    String DASHBOARD_STATISTICS = "DASHBOARD_STATISTICS";
    String MAINTAIN_SOLIDARITY_LEADER_ELECTIONS = "MAINTAIN_SOLIDARITY_LEADER_ELECTIONS";
}
